/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarIdRouteImport } from './routes/car.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarIdRoute = CarIdRouteImport.update({
  id: '/car/$id',
  path: '/car/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/factory': typeof FactoryRoute
  '/garage': typeof GarageRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/car/$id': typeof CarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/factory': typeof FactoryRoute
  '/garage': typeof GarageRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/car/$id': typeof CarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/factory': typeof FactoryRoute
  '/garage': typeof GarageRoute
  '/locations': typeof LocationsRoute
  '/login': typeof LoginRoute
  '/car/$id': typeof CarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand'
    | '/factory'
    | '/garage'
    | '/locations'
    | '/login'
    | '/car/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand'
    | '/factory'
    | '/garage'
    | '/locations'
    | '/login'
    | '/car/$id'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/factory'
    | '/garage'
    | '/locations'
    | '/login'
    | '/car/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  FactoryRoute: typeof FactoryRoute
  GarageRoute: typeof GarageRoute
  LocationsRoute: typeof LocationsRoute
  LoginRoute: typeof LoginRoute
  CarIdRoute: typeof CarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/$id': {
      id: '/car/$id'
      path: '/car/$id'
      fullPath: '/car/$id'
      preLoaderRoute: typeof CarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  FactoryRoute: FactoryRoute,
  GarageRoute: GarageRoute,
  LocationsRoute: LocationsRoute,
  LoginRoute: LoginRoute,
  CarIdRoute: CarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
